# This is a basic workflow to help you get started with Actions

name: Catalog Service Deployment WorkFlow In Development Enviroment 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
   # branches: [ "features/STRY-0333439-Setup-Prod-Environment" ]
  #pull_request:
   # branches: [ "master" ]
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set the value
        id: step_one
        run: |
          ls -l
          echo "FOO=$(git branch)" >> $GITHUB_ENV
      - name: Use the value     
        id: step_two
        run: |
          echo "${{ env.FOO }}"
          
  
  deploy-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure WebA
        id: step_three
        run: |
          echo "FOO=$(git branch)" >> $GITHUB_ENV
          echo "${{ env.FOO }}"
